### PR TITLE
Test env

### PR DESCRIPTION
**Pull request by jarekani**
This change is [Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/7)

### CODE REVIEW

**Review by chorig9 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/7)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @jarekani)

___
*[test-env/cmd_parser.py, line 5 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/7#-LlQki1pDRCfuxE0t2be:-LlQki1pDRCfuxE0t2bf:b-b3x55d) ([raw file](https://github.com/chorig9/dtn-sync/blob/b2b0a6f1ec679810dd02d661b483e443fd389e82/test-env/cmd_parser.py#L5)):*
> ```Python
> class CmdTypes:
>     CMD = "cmd"
>     ICMD = "icmd"   
> ```

what is ICMD?
___
*[test-env/template_env.json, line 3 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/7#-LlQkHXaAj67yLg4m-iD:-LlQkHXaAj67yLg4m-iE:bpun9do) ([raw file](https://github.com/chorig9/dtn-sync/blob/b2b0a6f1ec679810dd02d661b483e443fd389e82/test-env/template_env.json#L3)):*
> ```JSON
> {
> 	"config": {},	//currently not used
> 	"networks": [	//list of all networks, tip: use ip4  
> ```

in json, there can be no comments (if you try to pass this file to run_env.py it will fail). Since, this is a json file I think it should have the proper format

**Review by chorig9 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/7)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @jarekani)

___
*[test-env/env.py, line 59 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/7#-LlQsatt3tczWZONfOrm:-LlQsatu4L-H_YbmN6oU:b8u0iab) ([raw file](https://github.com/chorig9/dtn-sync/blob/b2b0a6f1ec679810dd02d661b483e443fd389e82/test-env/env.py#L59)):*
> ```Python
> 
>         for cmd in self.cmdParser.cmds:
>             if DataTypes.NODE_IP in cmd["cmd"]:
> ```

Could you explain what is happening in this if?

**Review by jarekani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/7)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @chorig9)

___
*[test-env/cmd_parser.py, line 5 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/7#-LlQki1pDRCfuxE0t2be:-LlSYeDa5RKFSeRtX1u8:b-2xqaip) ([raw file](https://github.com/chorig9/dtn-sync/blob/b2b0a6f1ec679810dd02d661b483e443fd389e82/test-env/cmd_parser.py#L5)):*
<details><summary><i>Previously, chorig9 (Igor Chorążewicz) wrote…</i></summary><blockquote>

what is ICMD?
</blockquote></details>

Is icmd method from https://github.com/coreemu/core/blob/master/daemon/core/nodes/client.py
As far I know it's basically  cmd with blocking.
___
*[test-env/env.py, line 59 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/7#-LlQsatt3tczWZONfOrm:-LlSXLc581PRkFsFbYVh:b4a89qn) ([raw file](https://github.com/chorig9/dtn-sync/blob/b2b0a6f1ec679810dd02d661b483e443fd389e82/test-env/env.py#L59)):*
<details><summary><i>Previously, chorig9 (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you explain what is happening in this if?
</blockquote></details>

DataTypes is a enum with diffrent macros type strings. In that specific if I was checking if command has "macro" for node ip address, later in code I replace it with ip of given node.
___
*[test-env/template_env.json, line 3 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/7#-LlQkHXaAj67yLg4m-iD:-LlSX3_3DHpUpzGcGlAN:b70wl9o) ([raw file](https://github.com/chorig9/dtn-sync/blob/b2b0a6f1ec679810dd02d661b483e443fd389e82/test-env/template_env.json#L3)):*
<details><summary><i>Previously, chorig9 (Igor Chorążewicz) wrote…</i></summary><blockquote>

in json, there can be no comments (if you try to pass this file to run_env.py it will fail). Since, this is a json file I think it should have the proper format
</blockquote></details>

I know that, but I wanted to explain some parts of JSON file. Maybe Swagger file will be better?

**Review by jarekani — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 7 files at r2, 5 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/7)* status: all files reviewed, 2 unresolved discussions (waiting on @chorig9)

___
*[test-env/cmd_parser.py, line 5 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/7#-LlQki1pDRCfuxE0t2be:-LlXYBo285QYX15c_jZL:b-896fix) ([raw file](https://github.com/chorig9/dtn-sync/blob/b2b0a6f1ec679810dd02d661b483e443fd389e82/test-env/cmd_parser.py#L5)):*
<details><summary><i>Previously, jarekani (Jarosław Aniołek) wrote…</i></summary><blockquote>

Is icmd method from https://github.com/coreemu/core/blob/master/daemon/core/nodes/client.py
As far I know it's basically  cmd with blocking.
</blockquote></details>

Done.

**Review by chorig9 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/7)* status: all files reviewed, 2 unresolved discussions (waiting on @jarekani)

___
*[test-env/run_env.py, line 6 at r3](https://reviewable.io/reviews/chorig9/dtn-sync/7#-LlYT_RU5Sxsreok0gmZ:-LlYT_RV8m0z_xEp42-z:b-9xng5f) ([raw file](https://github.com/chorig9/dtn-sync/blob/4a0e414be593ce56e165fab9fb74fd5100438526/test-env/run_env.py#L6)):*
> ```Python
> 
> parser = argparse.ArgumentParser()
> parser.add_argument("-c", "--commands_file", help="File containing list of commands for each node. More in readme", required=True)
> ```

Actually, I think this file is no longer needed. We can write tests in pure python.
___
*[test-env/template_env.json, line 3 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/7#-LlQkHXaAj67yLg4m-iD:-LlYTrIW-imHht3aJBpN:bfpya4a) ([raw file](https://github.com/chorig9/dtn-sync/blob/b2b0a6f1ec679810dd02d661b483e443fd389e82/test-env/template_env.json#L3)):*
<details><summary><i>Previously, jarekani (Jarosław Aniołek) wrote…</i></summary><blockquote>

I know that, but I wanted to explain some parts of JSON file. Maybe Swagger file will be better?
</blockquote></details>

I think format is pretty self-explantory. Maybe instead of comments here, just create some README?

**Review by jarekani — COMMENTED** [review]
> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/7)* status: all files reviewed, 2 unresolved discussions (waiting on @chorig9)

___
*[test-env/run_env.py, line 6 at r3](https://reviewable.io/reviews/chorig9/dtn-sync/7#-LlYT_RU5Sxsreok0gmZ:-Llble8I51yHuJRQfK0w:bb6un1j) ([raw file](https://github.com/chorig9/dtn-sync/blob/4a0e414be593ce56e165fab9fb74fd5100438526/test-env/run_env.py#L6)):*
<details><summary><i>Previously, chorig9 (Igor Chorążewicz) wrote…</i></summary><blockquote>

Actually, I think this file is no longer needed. We can write tests in pure python.
</blockquote></details>

Done
___
*[test-env/template_env.json, line 3 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/7#-LlQkHXaAj67yLg4m-iD:-LlblZyw2UjEN548khD0:b-896fix) ([raw file](https://github.com/chorig9/dtn-sync/blob/b2b0a6f1ec679810dd02d661b483e443fd389e82/test-env/template_env.json#L3)):*
<details><summary><i>Previously, chorig9 (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think format is pretty self-explantory. Maybe instead of comments here, just create some README?
</blockquote></details>

Done.

**Review by chorig9 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by chorig9 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/7#-:-LlcCoUS3bDdKhk2M1Ht:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by krupatomasz — APPROVED** [review]
LGTM

**Pull request merged**
