### PR TITLE
Add querying other nodes for file info

### PR DESCRIPTION
**Pull request by krupatomasz**
Built over #3. I will update this once it's merged

---
This change is [Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/4)

### CODE REVIEW

**Review by chorig9 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/4)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @chorig9, @jarekani, and @krupatomasz)

___
*[src/communication.py, line 22 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/4#-LlIIuDW2FoKh4URmeyQ:-LlIIuDW2FoKh4URmeyR:b-qhlfg7) ([raw file](https://github.com/chorig9/dtn-sync/blob/f274fb3a87bbd86e9417e08374235b56dc066441/src/communication.py#L22)):*
> ```Python
>             CONTENT = 1
>             QUERY = 2
>             ANSWER = 3
> ```

what is the purpose of ANSWER (what is the difference between this and CONTENT)? 
___
*[src/communication.py, line 76 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/4#-LlIJxz3B9ZG5XJWRBN-:-LlIJ1kWEi20DE1NjQ0A:b-9coah2) ([raw file](https://github.com/chorig9/dtn-sync/blob/f274fb3a87bbd86e9417e08374235b56dc066441/src/communication.py#L76)):*
> ```Python
>                 self.on_receive_callback(data.file_info, received_file)
>             elif data.type == Communicator.Data.Type.QUERY:
>                 port = 12345 # TODO: get dynamically once neighbour lookup table exists
> ```

maybe for now, let's just use self.port?
___
*[src/communication.py, line 107 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/4#-LlIILnQ4BVuNG-Zhjlm:-LlIILnQ4BVuNG-Zhjln:bknzj7s) ([raw file](https://github.com/chorig9/dtn-sync/blob/f274fb3a87bbd86e9417e08374235b56dc066441/src/communication.py#L107)):*
> ```Python
>         answer.type = Communicator.Data.Type.ANSWER
>         file_info = utils.get_file(self.sync_dir_path, query_data.file_info.file_basename)
>         if file_info != None:
> ```

why not answer.file_info = utils.get_file(...) ?

**Review by chorig9 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/4)* status: all files reviewed, 3 unresolved discussions (waiting on @jarekani and @krupatomasz)

**Review by krupatomasz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/4)* status: all files reviewed, 3 unresolved discussions (waiting on @chorig9, @jarekani, and @krupatomasz)

___
*[src/communication.py, line 22 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/4#-LlIIuDW2FoKh4URmeyQ:-LlNDn4hER6w8KpqhcY5:bq3zb9k) ([raw file](https://github.com/chorig9/dtn-sync/blob/f274fb3a87bbd86e9417e08374235b56dc066441/src/communication.py#L22)):*
<details><summary><i>Previously, chorig9 (Igor Chorążewicz) wrote…</i></summary><blockquote>

what is the purpose of ANSWER (what is the difference between this and CONTENT)? 
</blockquote></details>

Already answered in person, so just for record - it's to indicate we're sending just file metadata in response to a query, not the whole file.
___
*[src/communication.py, line 76 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/4#-LlIJxz3B9ZG5XJWRBN-:-LlNEvQq6zDq0zQiJclP:bebrt1w) ([raw file](https://github.com/chorig9/dtn-sync/blob/f274fb3a87bbd86e9417e08374235b56dc066441/src/communication.py#L76)):*
<details><summary><i>Previously, chorig9 (Igor Chorążewicz) wrote…</i></summary><blockquote>

maybe for now, let's just use self.port?
</blockquote></details>

Will do
___
*[src/communication.py, line 107 at r2](https://reviewable.io/reviews/chorig9/dtn-sync/4#-LlIILnQ4BVuNG-Zhjlm:-LlNEl1k6UnfkaCs6Uv8:b-nla47q) ([raw file](https://github.com/chorig9/dtn-sync/blob/f274fb3a87bbd86e9417e08374235b56dc066441/src/communication.py#L107)):*
<details><summary><i>Previously, chorig9 (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not answer.file_info = utils.get_file(...) ?
</blockquote></details>

Right, I'll change it.

**Review by jarekani — APPROVED** [review]
LGTM

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/4#-:-LlO6-1X9wydQwg1ewY0:b-85i64v)* status: all files reviewed, 3 unresolved discussions (waiting on @chorig9 and @krupatomasz)

**Review by chorig9 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/4)* status: all files reviewed, 5 unresolved discussions (waiting on @krupatomasz)

___
*[src/synchronization.py, line 17 at r3](https://reviewable.io/reviews/chorig9/dtn-sync/4#-LpIX5wx7SQ0UrmS-I4t:-LpIX5wx7SQ0UrmS-I4u:b-swpo3n) ([raw file](https://github.com/chorig9/dtn-sync/blob/2249629a397d0c0e066c855574b664248ee15761/src/synchronization.py#L17)):*
> ```Python
> 
>         self.update_in_progress = {""}
>         self.answers = {}
> ```

What exactly is stored here?
___
*[src/synchronization.py, line 30 at r3](https://reviewable.io/reviews/chorig9/dtn-sync/4#-LpIXw9k15RO_hHh-Lar:-LpIXw9l7SMLbmf9tgsw:bf3x07f) ([raw file](https://github.com/chorig9/dtn-sync/blob/2249629a397d0c0e066c855574b664248ee15761/src/synchronization.py#L30)):*
> ```Python
>                     self.answer_query(local_file_vcs, sender_address)
>             elif patch.type == vcs.FilePatch.Type.ANSWER:
>                 if patch.file_basename in self.answers:
> ```

what if it is not in self.answers?
___
*[src/synchronization.py, line 59 at r3](https://reviewable.io/reviews/chorig9/dtn-sync/4#-LpIYH522l2rO10kNT5P:-LpIYH522l2rO10kNT5Q:b-89d3im) ([raw file](https://github.com/chorig9/dtn-sync/blob/2249629a397d0c0e066c855574b664248ee15761/src/synchronization.py#L59)):*
> ```Python
> 
>     def wait_for_answers(self, filename):
>         time.sleep(5)
> ```

What if we get some reponse later than 5 sencond after? I think in data_received we should do something with this response.
___
*[src/synchronization.py, line 64 at r3](https://reviewable.io/reviews/chorig9/dtn-sync/4#-LpIYios3Q4PiTbSd_vx:-LpIYios3Q4PiTbSd_vy:b-arkwc9) ([raw file](https://github.com/chorig9/dtn-sync/blob/2249629a397d0c0e066c855574b664248ee15761/src/synchronization.py#L64)):*
> ```Python
>             newest_patch = None
>             for sender_address, patch in answer:
>                 if patch.get_version() > local_file_vcs.get_version():
> ```

RIght now, if last patch in answers list is bigger than local_file_vs it will be treated as newest_patch (event if former patches were newer). Shouldn't it be:

```
newest_patch = local_file_vcs
for sender, patch in answer:
    if patch.get_version() > newest_patch.get_version():
        newest_patch = patch
``` 
?

**Pull request closed without merging**
