### PR TITLE
Split SyncWorker implementation, simplify Communicator

### PR DESCRIPTION
**Pull request by chorig9**
and implement basic VersionControlSystem based on timestamps

---
This change is [Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/6)

### CODE REVIEW

**Review by jarekani — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/6)* status: all files reviewed, 1 unresolved discussion (waiting on @chorig9 and @krupatomasz)

___
*[src/vcs.py, line 39 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/6#-LlO4b3C28y5-DKGM87y:-LlO4b3C28y5-DKGM87z:b-k7aiep) ([raw file](https://github.com/chorig9/dtn-sync/blob/37d89a88869211ae8bbdfeea56a74f7c57cc787c/src/vcs.py#L39)):*
> ```Python
>             
>     def commit(self):
>         self.version_history.timestamp = time.time()
> ```

With this every node will have diffrent version.  Better, when reciving patch, set version to the patch's version.

**Review by chorig9 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/6)* status: all files reviewed, 1 unresolved discussion (waiting on @jarekani and @krupatomasz)

___
*[src/vcs.py, line 39 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/6#-LlO4b3C28y5-DKGM87y:-LlQhCZVC2Eqjn1rOFKG:b-896fix) ([raw file](https://github.com/chorig9/dtn-sync/blob/37d89a88869211ae8bbdfeea56a74f7c57cc787c/src/vcs.py#L39)):*
<details><summary><i>Previously, jarekani (Jarosław Aniołek) wrote…</i></summary><blockquote>

With this every node will have diffrent version.  Better, when reciving patch, set version to the patch's version.
</blockquote></details>

Done.

**Review by jarekani — COMMENTED** [review]
LGTM

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/6#-:-LlSWl6N2JGO0AmjF3hM:b-85i64v)* status: all files reviewed, 1 unresolved discussion (waiting on @jarekani and @krupatomasz)

**Comment by chorig9** [comment]
@krupatomasz does this look ok for you?

**Review by krupatomasz — APPROVED** [review]
LGTM

**Review by jarekani — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/6#-:-LlXZTmu8JhntXtccksV:bb6ywmx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
