### PR TITLE
Modify test env to support python tests

### PR DESCRIPTION
**Pull request by chorig9**
This change is [Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/8)

### CODE REVIEW

**Review by jarekani — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/8)* status: all files reviewed, 1 unresolved discussion (waiting on @chorig9)

___
*[test-env/env.py, line 15 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/8#-LlSZN08C-QP9qLdlmPC:-LlSZN08C-QP9qLdlmPD:b3lf6ru) ([raw file](https://github.com/chorig9/dtn-sync/blob/96bf3babb0538f39c36d1022c19e6e5448cc3675/test-env/env.py#L15)):*
> ```Python
> 
> class Env():
>     def __init__(self, env_config, silent=False):
> ```

IMHO it's unnecessary, in run_env.py file arg silent is set to False as default

**Review by chorig9 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/8)* status: all files reviewed, 1 unresolved discussion (waiting on @jarekani)

___
*[test-env/env.py, line 15 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/8#-LlSZN08C-QP9qLdlmPC:-LlT6gc_DRJeb8QgiWyt:boh56ti) ([raw file](https://github.com/chorig9/dtn-sync/blob/96bf3babb0538f39c36d1022c19e6e5448cc3675/test-env/env.py#L15)):*
<details><summary><i>Previously, jarekani (Jarosław Aniołek) wrote…</i></summary><blockquote>

IMHO it's unnecessary, in run_env.py file arg silent is set to False as default 
</blockquote></details>

But here, I do not use run_env.py. Instead I use python script where silent is not set

**Review by jarekani — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by chorig9** [comment]
@jarekani since this is pr to your branch - if you think it's ok, please merge

**Pull request merged**
