### PR TITLE
Implement rdiff support and fast-forward synchronization

### PR DESCRIPTION
**Pull request by chorig9**
This change is [Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/12)

### CODE REVIEW

**Review by jarekani — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/12)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @chorig9)

___
*[src/synchronization.py, line 17 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/12#-LpXBeuB4l10ZjMyHJsC:-LpXBeuC98jC7yBRqxOe:b9d38t6) ([raw file](https://github.com/chorig9/dtn-sync/blob/c6ab1cebb1d7087cfe94f9a2d7a7f0cdf3969363/src/synchronization.py#L17)):*
> ```Python
>         self.vcs = vcs.VCS(directory)
> 
>         # XXX: lock per file?
> ```

In case of large file or really slow network one lock would freez whole process, so lock per file is better option.
___
*[src/synchronization.py, line 26 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/12#-LpXDOyf6gR1pvQ1LFhi:-LpXDOyf6gR1pvQ1LFhj:b-28urvh) ([raw file](https://github.com/chorig9/dtn-sync/blob/c6ab1cebb1d7087cfe94f9a2d7a7f0cdf3969363/src/synchronization.py#L26)):*
> ```Python
> 
>     def _on_data_received(self, buffer):
>         # XXX: Additionally we should also prevent user from modyfing file? - user required to get lock from dtn-sync deamon?
> ```

That wouldn't work with any external software due to our deamon is only watching changes in filesystem. 
If we requre to get locks from deamon, all software have to be prepare to worj with that. 
Also if external software open file only for reading purposes and never reload file changes made by other nodes would never be seen by this softwere. 
Is there any option to check what version of file is used be external softwere?
Also AFIK each node would only modify it's files,no otheres. So situation when another node modify node's file I would treat as conflicts.
___
*[src/vcs.py, line 62 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/12#-LpXKg3d3Ragn1VShF38:-LpXKg3eCPm7pF1Zhq--:b-kv6sb5) ([raw file](https://github.com/chorig9/dtn-sync/blob/c6ab1cebb1d7087cfe94f9a2d7a7f0cdf3969363/src/vcs.py#L62)):*
> ```Python
>     def __init__(self, file_path):
>         self.file_path = file_path
>         self.version_history = VersionHistory() # XXX: store this in some DB (lsm-db?)
> ```

If I remeber corectly, git or another pice of softwere should keep history.
___
*[src/vcs.py, line 72 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/12#-LpXLIqAAklzUErCBf6a:-LpXLIqAAklzUErCBf6b:bupogh8) ([raw file](https://github.com/chorig9/dtn-sync/blob/c6ab1cebb1d7087cfe94f9a2d7a7f0cdf3969363/src/vcs.py#L72)):*
> ```Python
>     def commit(self):
>         c = Commit()
>         c.author = "SELF"
> ```

Id of author will be better in this place, it wolud allowed to compere logs and parse history easly.
___
*[src/vcs.py, line 127 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/12#-LpXMKtR350sLKY84IXE:-LpXMKtR350sLKY84IXF:bm9hnh) ([raw file](https://github.com/chorig9/dtn-sync/blob/c6ab1cebb1d7087cfe94f9a2d7a7f0cdf3969363/src/vcs.py#L127)):*
> ```Python
>                 shutil.move(conflict_res, self.file_path)
>                 os.remove(tmp_file)
>         # XXX, what if alread applied (commits from patch are already applied), can this even happen?
> ```

Only if patch would be duplicated be network in some point.

**Review by chorig9 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/12)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @chorig9 and @jarekani)

___
*[src/synchronization.py, line 17 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/12#-LpXBeuB4l10ZjMyHJsC:-LqW8iJu2wb1RDFqO8nv:bye1rnp) ([raw file](https://github.com/chorig9/dtn-sync/blob/c6ab1cebb1d7087cfe94f9a2d7a7f0cdf3969363/src/synchronization.py#L17)):*
<details><summary><i>Previously, jarekani (Jarosław Aniołek) wrote…</i></summary><blockquote>

In case of large file or really slow network one lock would freez whole process, so lock per file is better option.
</blockquote></details>

This lock is only for applying patch/bumping current version so it should not be so problematic
___
*[src/vcs.py, line 62 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/12#-LpXKg3d3Ragn1VShF38:-LqVzJuO9eRz9omVHeKl:b-qdvun5) ([raw file](https://github.com/chorig9/dtn-sync/blob/c6ab1cebb1d7087cfe94f9a2d7a7f0cdf3969363/src/vcs.py#L62)):*
<details><summary><i>Previously, jarekani (Jarosław Aniołek) wrote…</i></summary><blockquote>

If I remeber corectly, git or another pice of softwere should keep history.
</blockquote></details>

I think it's better to keep track of this ourselves (we just have to track list of which node modified the file). Git cannot be configured to track history per-file (we can have per-file repository but tghat's big overhead - several KB). Using other tools is also not possible (I tried some of them)
___
*[src/vcs.py, line 72 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/12#-LpXLIqAAklzUErCBf6a:-LqVzoH2BafKVmohlwhr:b-z8r6p) ([raw file](https://github.com/chorig9/dtn-sync/blob/c6ab1cebb1d7087cfe94f9a2d7a7f0cdf3969363/src/vcs.py#L72)):*
<details><summary><i>Previously, jarekani (Jarosław Aniołek) wrote…</i></summary><blockquote>

Id of author will be better in this place, it wolud allowed to compere logs and parse history easly.
</blockquote></details>

Sure, we just need some implementation for unique names. (Implementation which will retain name after application restart).

**Review by jarekani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/12)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @chorig9 and @jarekani)

___
*[src/vcs.py, line 72 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/12#-LpXLIqAAklzUErCBf6a:-Lqm8TsaEiSwpkmDzaiM:bby3ye6) ([raw file](https://github.com/chorig9/dtn-sync/blob/c6ab1cebb1d7087cfe94f9a2d7a7f0cdf3969363/src/vcs.py#L72)):*
<details><summary><i>Previously, chorig9 (Igor Chorążewicz) wrote…</i></summary><blockquote>

Sure, we just need some implementation for unique names. (Implementation which will retain name after application restart).
</blockquote></details>

AFAIK Bundle Protocol has it's one implementation of unique names, if we could use that, that would be the best option IMO

**Comment by chorig9** [comment]
Reimplemented in: https://github.com/chorig9/dtn-sync/pull/16

**Pull request closed without merging**
