### PR TITLE
Implement fast-forward and out-of-order synchronization

### PR DESCRIPTION
**Pull request by chorig9**
This change is [Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/18)

### CODE REVIEW

**Review by jarekani — APPROVED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/18)* status: all files reviewed, 3 unresolved discussions (waiting on @chorig9)

___
*[src/monitor.py, line 20 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/18#-Lsq0YE15FDR9gAFGzX8:-Lsq0YE15FDR9gAFGzX9:b-sho9t5) ([raw file](https://github.com/chorig9/dtn-sync/blob/dfe6d6e3429a77995209ec347ead5544b437110c/src/monitor.py#L20)):*
> ```Python
> 
>         # Check directory for events every 1000ms timeout=self.interval * 1000
>         self.notifier = pyinotify.Notifier(wm, event_handler, timeout=0)
> ```

Is timeout=0 just for now?
___
*[src/vcs.py, line 184 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/18#-LsqIPTW7Ly2YTgmUs9e:-LsqIPTW7Ly2YTgmUs9f:b-aq9gyq) ([raw file](https://github.com/chorig9/dtn-sync/blob/dfe6d6e3429a77995209ec347ead5544b437110c/src/vcs.py#L184)):*
> ```Python
>         dot_index = basename.index('.')
> 
>         new_basename1 = basename[:dot_index] + utils.get_node_name() + basename[dot_index:]
> ```

Why node name(id) is inside file name for conflicts? 
___
*[src/vcs.py, line 223 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/18#-LsqJVGFD69jaF3Pf857:-LsqJVGFD69jaF3Pf858:b-gbtjor) ([raw file](https://github.com/chorig9/dtn-sync/blob/dfe6d6e3429a77995209ec347ead5544b437110c/src/vcs.py#L223)):*
> ```Python
>             # Duplicated patch
>             pass
>         elif common_commits + 1 < len(patch.commits):
> ```

What with this case:
patches: A -> B 
received order: B->A

now in this case, patch B wouldn't be aplied until next patch arrived

**Review by chorig9 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/18)* status: all files reviewed, 3 unresolved discussions (waiting on @jarekani)

___
*[src/monitor.py, line 20 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/18#-Lsq0YE15FDR9gAFGzX8:-Lt6ThgD9si5QCo2A4Rn:biglo7r) ([raw file](https://github.com/chorig9/dtn-sync/blob/dfe6d6e3429a77995209ec347ead5544b437110c/src/monitor.py#L20)):*
<details><summary><i>Previously, jarekani (Jarosław Aniołek) wrote…</i></summary><blockquote>

Is timeout=0 just for now?
</blockquote></details>

Yes, this can be adjusted later, if this will take too much resources
___
*[src/vcs.py, line 184 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/18#-LsqIPTW7Ly2YTgmUs9e:-Lt6UPSyCDiEl2UKfIO-:b9m1aku) ([raw file](https://github.com/chorig9/dtn-sync/blob/dfe6d6e3429a77995209ec347ead5544b437110c/src/vcs.py#L184)):*
<details><summary><i>Previously, jarekani (Jarosław Aniołek) wrote…</i></summary><blockquote>

Why node name(id) is inside file name for conflicts? 
</blockquote></details>

This is WIP right now, I will implement conflict resolution properly in next PR. General idea is to just create 2 files which contain id of the authors in the name
___
*[src/vcs.py, line 223 at r1](https://reviewable.io/reviews/chorig9/dtn-sync/18#-LsqJVGFD69jaF3Pf857:-Lt6U4nm5VpzpxuU4aKI:b-xb02hs) ([raw file](https://github.com/chorig9/dtn-sync/blob/dfe6d6e3429a77995209ec347ead5544b437110c/src/vcs.py#L223)):*
<details><summary><i>Previously, jarekani (Jarosław Aniołek) wrote…</i></summary><blockquote>

What with this case:
patches: A -> B 
received order: B->A

now in this case, patch B wouldn't be aplied until next patch arrived
</blockquote></details>

That's right, I will fix this in next PR - this is just a matter of calling apply_patches in fast-forwad case

**Review by jarekani — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/18)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jarekani — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/chorig9/dtn-sync/18#-:-LtM07Dz4ho_jhGJd07F:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
